apiVersion: v1
kind: Service
metadata:
  name: {{ include "nr-exporter.fullname" . }}-svc
  labels:
    {{- include "nr-exporter.selectorLabels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: nr-exporter
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
