apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nr-exporter.fullname" . }}-config
  labels:
    {{- include "nr-exporter.selectorLabels" . | nindent 4 }}
data:
  newrelic_exporter.yml: |-
    api.key: {{ .Values.nrApiKey }}
    api.server: {{ .Values.nrServer }} 
    api.period: {{ .Values.nrPeriod }}
    api.timeout: {{ .Values.nrTimeout }}
    api.service: {{ .Values.nrService }}
    api.apps-list-cache-time: {{ .Values.nrAppsListCacheTime }}
    api.metric-names-cache-time: {{ .Values.nrMetricNamesCacheTime }}
    api.include-apps: {{ .Values.nrIncludeApps }}
    api.use-only-summary: {{ .Values.nrUseOnlySummary }}
    api.include-metric-filters: {{ .Values.nrIncludeMetricFilters }}
    api.include-values: {{ .Values.nrIncludeValues }}
    web.listen-address: ":{{ .Values.service.port }}"
    web.telemetry-path: "{{ .Values.nrTelemetryPath }}"
    {{- if .Values.nrDebug }}
    debug.proxy-address: "{{ .Values.nrDebugProxyAddress }}"
    {{ else }}
    # debug.proxy-address: "{{ .Values.nrDebugProxyAddress }}"
    {{- end }}