name: newrelic exporter build
on:
  push:
    tags:
      - "v*"
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build image and push"
      
      - name: prepare vars
        run: |
          set -xue
          TARGET_VERSION=${GITHUB_REF_NAME}

          echo "TARGET_VERSION=${TARGET_VERSION}" >> $GITHUB_ENV

      - name: check repo code
        uses: actions/checkout@v2
      
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: build docker image
        run: |
          set -ue
          docker build -t coraopensource/newrelic-exporter:${TARGET_VERSION} .
      
      - run: echo "This job's status is ${{ job.status }}."
      
      - name: login docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: push images
        run: |
          set -ue
          docker tag coraopensource/newrelic-exporter:${TARGET_VERSION} coraopensource/newrelic-exporter:latest
          docker push coraopensource/newrelic-exporter:${TARGET_VERSION}
          docker push coraopensource/newrelic-exporter:latest
      
      - run: echo "This job's status is ${{ job.status }}."
