name: newrelic exporter build
on:
  push:
    tags:
      - "v*"
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build image and push for tag ${{ github.ref }}"
      
      - name: check repo code
        uses: actions/checkout@v2
      
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
            
      - name: build docker image
        run: |
          docker build -t devopscora/newrelic-exporter:${{ github.ref }} .
      
      - run: echo "This job's status is ${{ job.status }}."
      
      - name: login docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: push images
        run: |
          docker tag devopscora/newrelic-exporter:${{ github.ref }} corabank/newrelic-exporter:latest
          docker push devopscora/newrelic-exporter:${{ github.ref }}
          docker push devopscora/newrelic-exporter:latest
      
      - run: echo "This job's status is ${{ job.status }}."
